### ISSUE TITLE
Cannot compile on Ubuntu 18.10 - efiprot.h include missing

### ISSUE THREAD

**Issue by kcleung** [0xbb/apple_set_os.efi#15]
I am running Ubuntu 18.10 on my Macbook Pro late 2013.  However, when I tried to compile, it shows the following compiler error:

cc -I/usr/include/efi -I/usr/include/efi/x86_64 -DGNU_EFI_USE_MS_ABI -fPIC -fshort-wchar -ffreestanding -fno-stack-protector -maccumulate-outgoing-args -Wall -Dx86_64 -Werror -m64 -mno-red-zone   -c -o apple_set_os.o apple_set_os.c
In file included from apple_set_os.c:7:
/usr/include/efi/efiapi.h:856:5: error: unknown type name ‘EFI_IMAGE_UNLOAD’
     EFI_IMAGE_UNLOAD                UnloadImage;
     ^~~~~~~~~~~~~~~~
make: *** [<builtin>: apple_set_os.o] Error 1

It turns out that the source file needs to explicitly:

#include <efiprot.h>

which defines EFI_IMAGE_UNLOAD

**Comment by kcleung** [comment]
This fix is in the pull request #11 please pull
